### ISSUE TITLE
file caption

### ISSUE THREAD

**Issue by ghost** [yash-dk/Mesh-RenameBot#2]
please make file caption base on file name

**Comment by yash-dk** [comment]
Means make custom caption??

**Comment by yuno74** [comment]
maybe make choose to enable custom caption or use file name as caption

**Comment by yash-dk** [comment]
Oh got it 👍

**Comment by ManuKriz** [comment]
I have added caption, merge my pull request yash-dk

**Comment by ManuKriz** [comment]
I have added caption, merge my pull request  @yash-dk

**Comment by yash-dk** [comment]
> I have added caption, merge my pull request @yash-dk

Done Thanks for that. 👍
