### ISSUE TITLE
DB ERROR ?

### ISSUE THREAD

**Issue by nikhileashy** [yash-dk/Mesh-RenameBot#4]
<html>
<body>

16 Aug, 10:29:53.851 | File "/usr/local/lib/python3.9/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker
-- | --
16 Aug, 10:29:53.851 | await handler.callback(self.client, *args)
16 Aug, 10:29:53.851 | File "/usr/src/app/MeshRenameBot/core/mode_select.py", line 13, in upload_mode
16 Aug, 10:29:53.851 | udb = UserDB()
16 Aug, 10:29:53.851 | File "/usr/src/app/MeshRenameBot/database/mongo_impl.py", line 14, in __init__
16 Aug, 10:29:53.851 | super().__init__(dburl)
16 Aug, 10:29:53.851 | File "/usr/src/app/MeshRenameBot/database/mongo_db.py", line 8, in __init__
16 Aug, 10:29:53.851 | self._client = MongoClient(dburl)
16 Aug, 10:29:53.851 | File "/usr/local/lib/python3.9/site-packages/pymongo/mongo_client.py", line 680, in __init__
16 Aug, 10:29:53.851 | seeds.update(uri_parser.split_hosts(entity, port))
16 Aug, 10:29:53.851 | File "/usr/local/lib/python3.9/site-packages/pymongo/uri_parser.py", line 359, in split_hosts
16 Aug, 10:29:53.851 | raise ConfigurationError("Empty host "
16 Aug, 10:29:53.851 | pymongo.errors.ConfigurationError: Empty host (or extra comma in host list)

</body>
</html>

**Comment by yash-dk** [comment]
i think the db url is not correct of the format in which it Is entered is not correct.

**Comment by nikhileashy** [comment]
python 3.6 or later ?

**Comment by yash-dk** [comment]
Yess
